apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dev-env-ci
spec:
  entrypoint: dev-env-ci
  templates:
  - name: dev-env-ci
    inputs:
      parameters:
      - name: repoRef
      - name: repoFullName
        value: jali-clarke/dev-env
      - name: reportContext
        value: build
    dag:
      tasks:
      - name: report-scheduled
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: context
            value: "{{inputs.parameters.reportContext}}"
          - name: state
            value: pending
          - name: description
            value: build scheduled
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: build
        depends: report-scheduled
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: repoRef
            value: "{{inputs.parameters.repoRef}}"
          - name: reportContext
            value: "{{inputs.parameters.reportContext}}"
        template: build

      - name: report-suceeded
        depends: build.Succeeded
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: context
            value: "{{inputs.parameters.reportContext}}"
          - name: state
            value: success
          - name: description
            value: build and deploy commit (if any) succeeded
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: report-failed
        depends: build.Failed
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: context
            value: "{{inputs.parameters.reportContext}}"
          - name: state
            value: failure
          - name: description
            value: build or deploy commit failed
        templateRef:
          name: github-commit-status
          template: github-commit-status

  - name: build
    synchronization:
      mutex:
        name: dev-env-ci-build
    inputs:
      parameters:
      - name: repoFullName
      - name: repoRef
      - name: reportContext
    dag:
      tasks:
      - name: report-running
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: context
            value: "{{inputs.parameters.reportContext}}"
          - name: state
            value: pending
          - name: description
            value: build running
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: build-image
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: repoRef
            value: "{{inputs.parameters.repoRef}}"
          - name: action
            value: run
        templateRef:
          name: nix-flakes
          template: nix-flakes-github
