apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dev-env-ci
spec:
  entrypoint: dev-env-ci
  templates:
  - name: dev-env-ci
    inputs:
      parameters:
      - name: repoFullName
      - name: repoRef
    dag:
      tasks:
      - name: report-scheduled
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: state
            value: scheduled
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: report-running
        depends: report-scheduled
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: state
            value: running
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: build
        depends: report-scheduled
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: repoRef
            value: "{{inputs.parameters.repoRef}}"
          - name: action
            value: run
        templateRef:
          name: nix-flakes
          template: nix-flakes-github

      - name: report-suceeded
        depends: build.Succeeded
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: state
            value: suceeded
        templateRef:
          name: github-commit-status
          template: github-commit-status

      - name: report-failed
        depends: build.Failed
        arguments:
          parameters:
          - name: repoFullName
            value: "{{inputs.parameters.repoFullName}}"
          - name: commitSha
            value: "{{inputs.parameters.repoRef}}"
          - name: state
            value: failed
        templateRef:
          name: github-commit-status
          template: github-commit-status
