apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nix-flakes
spec:
  entrypoint: nix-flakes-github
  templates:
  - name: nix-flakes-github
    inputs:
      parameters:
      - name: repoFullName
      - name: repoRef
      - name: action
        default: build
        enum:
        - build
        - run
      - name: extraBuildFlags
        default: "-v"
      - name: bootstrapDerivations
        default: "bash git nixFlakes openssh"
    nodeSelector:
      kubernetes.io/arch: amd64
    script:
      image: nixos/nix:2.3.12
      command: [nix-shell]
      source: |
        #!/usr/bin/env nix-shell
        #!nix-shell -p {{inputs.parameters.bootstrapDerivations}}
        #!nix-shell -i bash
        set +xeo pipefail

        git config --global user.name "jali-clarke"
        git config --global user.email "jinnah.ali-clarke@outlook.com"

        mkdir -p ~/.ssh
        cp /ssh-config/config ~/.ssh/config

        # we need to set NIX_CONF_DIR *after* having done the initial "nix-shell -p ..."
        export NIX_CONF_DIR=/nix-conf

        NIX_BUILD_FLAGS="--print-build-logs {{inputs.parameters.extraBuildFlags}}"

        # without the ulimit set below for open fds, we see the following error:
        # > fakeroot internal error #43: Identifier removed
        # > semop(2): encountered an error: Invalid argument
        ulimit -n 20000

        nix {{inputs.parameters.action}} $NIX_BUILD_FLAGS github:{{inputs.parameters.repoFullName}}/{{inputs.parameters.repoRef}}
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      volumeMounts:
      - name: cache-signing-key
        mountPath: /cache-signing-key
      - name: git-ssh-key
        mountPath: /git-ssh-key
      - name: nix-conf
        mountPath: /nix-conf
      - name: nix-worker-scripts
        mountPath: /nix-worker-scripts
      - name: ssh-config
        mountPath: /ssh-config
    volumes:
    - name: cache-signing-key
      secret:
        secretName: cache-signing-key
        defaultMode: 0400
    - name: git-ssh-key
      secret:
        secretName: workers-ssh-key
        defaultMode: 0400
    - name: nix-conf
      secret:
        secretName: nix-worker-nix-conf
        defaultMode: 0400
    - name: nix-worker-scripts
      configMap:
        name: nix-worker-scripts
        defaultMode: 0555
    - name: ssh-config
      configMap:
        name: nix-worker-ssh-config
