apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: emby-config-pv
