apiVersion: batch/v1
kind: Job
metadata:
  generateName: cert-fetcher-manual-
  namespace: cloudflare
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - env:
        - name: CERT_NAME
          value: jali-clarke-ca
        - name: DOMAINS
          value: jali-clarke.ca,*.jali-clarke.ca
        - name: CF_EMAIL
          valueFrom:
            secretKeyRef:
              key: CF_EMAIL
              name: credentials
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              key: CF_API_KEY
              name: credentials
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: nexus.jali-clarke.ca:5000/cert-fetcher
        imagePullPolicy: Always
        name: cert-fetcher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cert-fetcher
      serviceAccountName: cert-fetcher
      terminationGracePeriodSeconds: 30
