apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- secret.yaml
patches:
- root-pw-patch.yaml
- volume-mounts-patch.yaml
