apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-data
  nfs: # should be nfsv4 - see https://dev.mysql.com/doc/refman/8.0/en/disk-issues.html
    path: /mnt/storage/k8s_drive/mysql_data
    server: atlas.jali-clarke.ca
