apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: <path:kv/data/cloudflare#email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: <path:kv/data/cloudflare#email>
          apiKeySecretRef:
            name: cloudflare-credentials
            key: api-key
