# these pins are needed because the `latest` tags are used in the manifests for some reason

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
spec:
  template:
    spec:
      containers:
      - name: argo-rollouts
        image: quay.io/argoproj/argo-rollouts:v1.3.1
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts-dashboard
spec:
  template:
    spec:
      containers:
      - name: argo-rollouts-dashboard
        image: quay.io/argoproj/kubectl-argo-rollouts:v1.3.1
        imagePullPolicy: IfNotPresent
