apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
- https://raw.githubusercontent.com/argoproj/argo-rollouts/e243276b10c6094710609871b9f300d0cbbd397b/manifests/dashboard-install.yaml
- https://raw.githubusercontent.com/argoproj/argo-rollouts/e243276b10c6094710609871b9f300d0cbbd397b/manifests/install.yaml
- namespace.yaml
patches:
- image-tag-patch.yaml
