apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
- https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.3.1/manifests/dashboard-install.yaml
- https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.3.1/manifests/install.yaml
- namespace.yaml
patches:
- image-tag-patch.yaml
