apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-the-services-services
spec:
  generators:
  - list:
      elements:
      - serviceName: cassandra
      - serviceName: dev
      - serviceName: emby
      - serviceName: nix-cache
      - serviceName: torrents
  template:
    metadata:
      name: "{{serviceName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/jali-clarke/homelab-config.git
        targetRevision: master
        path: "k8s/{{serviceName}}/overlay"
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{serviceName}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: false
