apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  # override this with a generator providing the following params:
  #   ingressType
  #   ingressResourceName
  #   ingressPublishService
  #   loadBalancerIP
  generators: []
  template:
    metadata:
      name: "{{ingressResourceName}}"
    spec:
      project: basic-infrastructure
      source:
        helm:
          values: |
            controller:
              service:
                loadBalancerIP: "{{loadBalancerIP}}"
                externalTrafficPolicy: Local
              ingressClassByName: true
              ingressClassResource:
                enabled: true
                name: "{{ingressType}}"
                controllerValue: "k8s.io/{{ingressResourceName}}"
              publishService:
                enabled: true
                pathOverride: "{{ingressPublishService}}"
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: "4.0.3"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ingressResourceName}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: false
