apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadOnlyMany
  storageClassName: jellyfin-media-pv
  nfs:
    path: /mnt/storage/data_drive/iPod
    server: atlas.jali-clarke.ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: jellyfin-config-pv
  nfs:
    path: /mnt/storage/k8s_drive/jellyfin_config
    server: atlas.jali-clarke.ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: jellyfin-cache-pv
  nfs:
    path: /mnt/storage/k8s_drive/jellyfin_cache
    server: atlas.jali-clarke.ca
