apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dev-env-ci
spec:
  entrypoint: dev-env-ci
  templates:
  - name: dev-env-ci
    inputs:
      parameters:
      - name: repoRef
        default: HEAD
      - name: extraBuildFlags
        default: ""
    nodeSelector:
      kubernetes.io/arch: amd64
    script:
      image: nixos/nix:2.3.12
      command: [nix-shell]
      source: |
        #!/usr/bin/env nix-shell
        #!nix-shell -p bash git nixFlakes openssh bash
        #!nix-shell -i bash
        set +xeo pipefail

        mkdir -p ~/.ssh
        cp /ssh-config/config ~/.ssh/config

        # we need to set NIX_CONF_DIR *after* having done the initial "nix-shell -p ..."
        export NIX_CONF_DIR=/nix-conf

        git clone git@github.com:jali-clarke/dev-env
        cd dev-env
        git reset --hard {{inputs.parameters.repoRef}}

        NIX_BUILD_FLAGS="--print-build-logs {{inputs.parameters.extraBuildFlags}}"

        nix build $NIX_BUILD_FLAGS .
      volumeMounts:
      - name: git-ssh-key
        mountPath: /git-ssh-key
      - name: nix-conf
        mountPath: /nix-conf
      - name: ssh-config
        mountPath: /ssh-config
    volumes:
    - name: git-ssh-key
      secret:
        secretName: workers-ssh-key
        defaultMode: 0400
    - name: nix-conf
      configMap:
        name: nix-worker-nix-conf
    - name: ssh-config
      configMap:
        name: nix-worker-ssh-config
