apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: basic-infrastructure-services
spec:
  generators:
  - list:
      elements:
      - serviceName: argo-events
      - serviceName: argo-rollouts
      - serviceName: argo-workflows
      - serviceName: argo-workflows-workspace
      - serviceName: argocd
      - serviceName: cert-manager
      - serviceName: ddns
      - serviceName: external-dns
      - serviceName: metallb-system
      - serviceName: oauth2-proxy
  template:
    metadata:
      name: "{{serviceName}}"
    spec:
      project: basic-infrastructure
      source:
        repoURL: https://github.com/jali-clarke/homelab-config.git
        targetRevision: master
        plugin:
          name: argocd-vault-plugin-kustomize
        path: "k8s/{{serviceName}}/overlay"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{serviceName}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: false
