apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=ingress
        - --registry=txt
        - --txt-prefix=external-dns-txt.
        - --domain-filter=jali-clarke.ca
        - --provider=cloudflare
        # see https://github.com/kubernetes-sigs/external-dns/issues/1975
        - --annotation-filter=jali-clarke.external-dns.alpha.kubernetes.io/is-external in (true)
        envFrom:
        - secretRef:
            name: cloudflare-credentials
