apiVersion: v1
kind: Service
metadata:
  name: ingress-cname-target
spec:
  type: ExternalName
  externalName: ingress.jali-clarke.ca
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-external-cname-target
spec:
  type: ExternalName
  externalName: ingress-external.jali-clarke.ca
