- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --auth-mode
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: sso
- op: replace
  path: /spec/template/spec/containers/0/image
  value: quay.io/argoproj/argocli:v3.3.6
