apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# see also when updating:
# - argo-server-config-json6902-patch.yaml
# - workflow-controller-image-json6902-patch.yaml
- https://raw.githubusercontent.com/argoproj/argo-workflows/v3.3.8/manifests/namespace-install.yaml
patches:
- disable-tls-patch.yaml
- workflow-controller-config-patch.yaml
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: argo-server
  path: argo-server-config-json6902-patch.yaml
- target:
    version: v1
    group: apps
    kind: Deployment
    name: workflow-controller
  path: workflow-controller-image-json6902-patch.yaml
