# see https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml for all options
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowRestrictions: |
    templateReferencing: Secure

  parallelism: "3"
  namespaceParallelism: "3"

  resourceRateLimit: |
    limit: 5
    burst: 2

  nodeEvents: |
    enabled: false
