# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/eb19a103-39b7-4bf9-9bb2-f7143f58cd8f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4391-79D5";
      fsType = "vfat";
    };

  fileSystems."/mnt/backups" =
    {
      device = "backups";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/67f6bc68-7401-474d-afa6-e010b738d3f5"; }];

}
