apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
- https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/metallb.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/namespace.yaml
