apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
rules:
- apiGroups:
  - argoproj.io
  verbs:
  - "*"
  resources:
  - workflows
  - workflowtemplates
  - cronworkflows
