apiVersion: v1
kind: Secret
metadata:
  name: cache-signing-key
stringData:
  signing_key: <path:kv/data/argo/cache-signing-key#signing_key>
  signing_key.pub: <path:kv/data/argo/cache-signing-key#signing_key.pub>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook
type: Opaque
stringData:
  token: <path:kv/data/argo/github-webhook#personal-access-token>
  secret: <path:kv/data/argo/github-webhook#webhook-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: nix-worker-nix-conf
stringData:
  nix.conf: |
    experimental-features = nix-command flakes
    max-jobs = 2
    sandbox = false
    secret-key-files = /cache-signing-key/signing_key
    substituters = ssh://root@cache.nix-cache?priority=10 https://cache.nixos.org?priority=100
    trusted-public-keys = <path:kv/data/dev/cache-signing-key#signing_key.pub> cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
---
apiVersion: v1
kind: Secret
metadata:
  name: workers-ssh-key
type: Opaque
stringData:
  id_argo_workers: <path:kv/data/argo/workers-ssh-key#id_argo_workers>
  id_argo_workers.pub: <path:kv/data/argo/workers-ssh-key#id_argo_workers.pub>
