apiVersion: v1
kind: Secret
metadata:
  name: github-webhook
type: Opaque
stringData:
  token: <path:kv/data/argo/github-webhook#personal-access-token>
  secret: <path:kv/data/argo/github-webhook#webhook-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: workers-ssh-key
type: Opaque
stringData:
  id_argo_workers: <path:kv/data/argo/workers-ssh-key#id_argo_workers>
  id_argo_workers.pub: <path:kv/data/argo/workers-ssh-key#id_argo_workers.pub>
