apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  generators:
  - list:
      elements:
      - ingressType: internal
        ingressResourceName: ingress-nginx-internal
        ingressPublishService: external-dns/ingress-cname-target
        loadBalancerIP: "192.168.0.200"
      - ingressType: external
        ingressResourceName: ingress-nginx-external
        ingressPublishService: external-dns/ingress-external-cname-target
        loadBalancerIP: "192.168.0.202"
