apiVersion: v1
kind: ConfigMap
metadata:
  name: nix-worker-nix-conf
data:
  nix.conf: |
    experimental-features = nix-command flakes
    sandbox = false
    substituters = ssh://root@cache.nix-cache?priority=10 https://cache.nixos.org?priority=100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nix-worker-ssh-config
data:
  config: |
    StrictHostKeyChecking accept-new
    Host *
      IdentityFile /git-ssh-key/id_argo_workers
