apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    homelab:
      repositories:
      - owner: jali-clarke
        names:
        - dev-env
        - homelab-config
        - homelab-secrets
      webhook:
        endpoint: /github
        port: "12000"
        method: POST
        url: https://events.argo.jali-clarke.ca
      events:
      - "*"
      apiToken:
        name: github-webhook
        key: token
      webhookSecret:
        name: github-webhook
        key: secret
      insecure: true
      active: true
      contentType: json
