apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
bases:
- ../base
resources:
- eventsource.yaml
- ingress.yaml
- role.yaml
- rolebinding.yaml
- secret.yaml
- serviceaccount.yaml
patches:
- worker-controller-configmap-patch.yaml
