apiVersion: v1
kind: Secret
metadata:
  name: oauth2-secret
stringData:
  client-id: <path:kv/data/argo/oauth2#client-id>
  client-secret: <path:kv/data/argo/oauth2#client-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-access
type: Opaque
stringData:
  token: <path:kv/data/argo/github-webhook#personal-access-token>
  secret: <path:kv/data/argo/github-webhook#webhook-secret>
