# see https://argoproj.github.io/argo-workflows/argo-server-sso/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'homelab-admin' in groups"
