apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin-service
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.8.9-amd64
        resources:
          requests:
            cpu: 1000m
            memory: 3072Mi
          limits:
            cpu: 2000m
            memory: 7680Mi
        ports:
        - name: jellyfin-web
          containerPort: 8096
