apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-the-services
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps-of-apps
  source:
    repoURL: https://github.com/jali-clarke/homelab-config.git
    targetRevision: master
    path: k8s/applicationsets/all-the-services/components
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
