apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-fetcher
  namespace: cloudflare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-fetcher-role
  namespace: cloudflare
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-fetcher-role-binding
  namespace: cloudflare
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-fetcher-role
subjects:
- kind: ServiceAccount
  name: cert-fetcher
  namespace: cloudflare
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-fetcher
  namespace: cloudflare
spec:
  schedule: "0 0 1 */2 *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: cert-fetcher
          restartPolicy: Never
          containers:
          - name: cert-fetcher
            image: nexus.jali-clarke.ca:5000/cert-fetcher
            env:
            - name: CERT_NAME
              value: jali-clarke-ca
            - name: DOMAINS
              value: "jali-clarke.ca,*.jali-clarke.ca"
            - name: CF_EMAIL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: CF_EMAIL
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: CF_API_KEY
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
