apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-manager
  namespace: cloudflare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-manager-role
  namespace: cloudflare
rules:
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-manager-role
subjects:
  - kind: ServiceAccount
    name: dns-manager
    namespace: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-manager
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-manager
  template:
    metadata:
      labels:
        app: dns-manager
    spec:
      serviceAccountName: dns-manager
      containers:
      - name: dns-manager
        image: nexus.lan:5000/dns-manager
        env:
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: credentials
              key: CF_EMAIL
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: CF_API_KEY
        - name: ZONE
          value: jali-clarke.ca
        - name: INGRESS_ROOT
          value: ingress-root
        - name: INGRESS_CLASS
          value: external