apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.3.0/manifests/install.yaml
- clusterrolebinding.yaml
- namespace.yaml
- serviceaccount.yaml
patchesStrategicMerge:
- https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.6.0/manifests/argocd-cm.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.6.0/manifests/argocd-repo-server-deploy.yaml
- disable-tls-patch.yaml
- use-repo-server-sa-patch.yaml
