apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-external
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    jali-clarke.external-dns.alpha.kubernetes.io/is-external: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.jali-clarke.ca/oauth2/auth?allowed_groups=%2Fhomelab-admin"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.jali-clarke.ca/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri"
spec:
  ingressClassName: external
  tls:
  - hosts:
    - dev.jali-clarke.ca
    - files.dev.jali-clarke.ca
    - web.dev.jali-clarke.ca
    - staging.dev.jali-clarke.ca
    - files.staging.dev.jali-clarke.ca
    - web.staging.dev.jali-clarke.ca
    secretName: jali-clarke-ca
  rules:
  - host: dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-service
            port:
              number: 8080
  - host: files.dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-service
            port:
              number: 80
  - host: web.dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-service
            port:
              number: 8888
  - host: staging.dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-staging-service
            port:
              number: 8080
  - host: files.staging.dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-staging-service
            port:
              number: 80
  - host: web.staging.dev.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: coder-staging-service
            port:
              number: 8888
