apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: dev
stringData:
  id_dev_env: <path:kv/data/dev/git-ssh-key#id_dev_env>
  id_dev_env.pub: <path:kv/data/dev/git-ssh-key#id_dev_env.pub>
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-signing-key
  namespace: dev
stringData:
  signing_key: <path:kv/data/dev/cache-signing-key#signing_key>
  signing_key.pub: <path:kv/data/dev/cache-signing-key#signing_key.pub>
