- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: dev-data
    persistentVolumeClaim:
      claimName: dev-data-pvc
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: ssh-key
    secret:
      secretName: git-ssh-key
      defaultMode: 0400
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: cache-signing-key
    secret:
      secretName: cache-signing-key
      defaultMode: 0400
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: nix-conf
    secret:
      secretName: nix-conf
      defaultMode: 0444
