apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
bases:
- github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.13.1
patches:
- clusterrolebinding-fix-patch.yaml
