apiVersion: v1
kind: ConfigMap
metadata:
  name: file-browser-nginx-config
  namespace: dev
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }
    http {
      server {
        root /www/data;

        location / {
          types {
            video/webm webm;
          }

          autoindex on;
        }
      }
    }
