# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3bab93fe-9c68-4fd0-9aa0-7fea228d3654";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4F94-D222";
      fsType = "vfat";
    };

  fileSystems."/mnt/storage/atlas_services/pihole" =
    {
      device = "storage/pihole";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/atlas_services/nexus_data" =
    {
      device = "storage/nexus_data";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/atlas_services/vault_data" =
    {
      device = "storage/vault_data";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/cassandra" =
    {
      device = "storage/cassandra";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/dev" =
    {
      device = "storage/dev";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/emby_config" =
    {
      device = "storage/emby_config";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/mysql_data" =
    {
      device = "storage/mysql_data";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/qbittorrent" =
    {
      device = "storage/qbittorrent";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/k8s_drive/tf2_data" =
    {
      device = "storage/tf2_data";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/data_drive" =
    {
      device = "storage/data_drive";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/data_drive/Torrents" =
    {
      device = "storage/torrents_download";
      fsType = "zfs";
    };

  fileSystems."/mnt/storage/backup_drive" =
    {
      device = "storage/backup_drive";
      fsType = "zfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/9e282a4c-9780-40e8-b726-2cfa417768f1"; }];

}
