# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3bab93fe-9c68-4fd0-9aa0-7fea228d3654";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4F94-D222";
      fsType = "vfat";
    };

  fileSystems."/mnt/storage" =
    { device = "storage";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9e282a4c-9780-40e8-b726-2cfa417768f1"; }
    ];

}
