apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:14.3.4.99202103270406-7346-81a7b0c03ubuntu20.04.1-ls123
        env:
        - name: TZ
          value: America/Toronto
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - name: webui
          containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: downloads-volume
          mountPath: /downloads
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: torrents-downloads-pvc
