apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: <path:kv/data/argocd#admin-password-hash>
  admin.passwordMtime: <path:kv/data/argocd#admin-password-mtime>
  oidc.keycloak.clientID: <path:kv/data/oauth2/argocd#client-id>
  oidc.keycloak.clientSecret: <path:kv/data/oauth2/argocd#client-secret>
  webhook.github.secret: <path:kv/data/argocd#webhook-github-secret>
