apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        env:
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: AVP_K8S_ROLE
          value: repo-server
        - name: AVP_TYPE
          value: vault
        - name: VAULT_ADDR
          value: http://vault.jali-clarke.ca
