apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-external
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: external
  tls:
  - hosts:
    - argocd.jali-clarke.ca
    secretName: jali-clarke-ca
  rules:
  - host: argocd.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port:
              number: 80
