apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
- ../base
resources:
- ingress.yaml
patches:
- add-avp-env-vars.yaml
- add-configmap-data.yaml
- add-rbac-configmap-data.yaml
- add-secret-data.yaml
