apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: eventbus-controller
  path: managed-namespace-json6902-patch.yaml
- target:
    version: v1
    group: apps
    kind: Deployment
    name: eventsource-controller
  path: managed-namespace-json6902-patch.yaml
- target:
    version: v1
    group: apps
    kind: Deployment
    name: sensor-controller
  path: managed-namespace-json6902-patch.yaml
