apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.0
        command:
        - /opt/keycloak/bin/kc.sh
        - start
        args:
        - --auto-build
        - --db=$DB_VENDOR
        - --db-url-host=$DB_ADDR:$DB_PORT
        - --db-url-database=$DB_DATABASE
        - --db-username=$DB_USER
        - --db-password=$DB_PASSWORD
        - --http-enabled=true
        - --proxy=passthrough
        # this is intended to run behind a proxy that verifies host header
        - --hostname-strict=false
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
