apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
spec:
  source:
    helm:
      # see the below on how to config this better
      # https://argocd-vault-plugin.readthedocs.io/en/stable/usage/#with-helm
      values: |
        grafana:
          adminPassword: <path:kv/data/monitoring#grafana-password>
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            ingressClassName: internal
            hosts:
            - grafana.jali-clarke.ca
            tls:
            - hosts:
              - grafana.jali-clarke.ca
              secretName: jali-clarke-ca
