apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- secrets.yaml
patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: cache
  path: volumes-patch-cache.json6902.yaml
