apiVersion: v1
kind: Secret
metadata:
  name: coder-password
stringData:
  coder-password: <path:kv/data/dev/coder-password#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-ssh-key
stringData:
  id_dev_env.pub: <path:kv/data/dev/git-ssh-key#id_dev_env.pub>
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-ssh-host-key
stringData:
  ssh_host_rsa_key: <path:kv/data/dev/cache-ssh-host-key#ssh_host_rsa_key>
  ssh_host_rsa_key.pub: <path:kv/data/dev/cache-ssh-host-key#ssh_host_rsa_key.pub>
