apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  ingressClassName: internal
  rules:
  - host: keycloak.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keycloak
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-external
spec:
  ingressClassName: external
  tls:
  - hosts:
    - keycloak.jali-clarke.ca
    secretName: jali-clarke-ca
  rules:
  - host: keycloak.jali-clarke.ca
    http:
      paths:
      - pathType: Prefix
        path: "/auth/realms/homelab"
        backend:
          service:
            name: keycloak
            port:
              number: 8080
      - pathType: Prefix
        path: "/auth/resources"
        backend:
          service:
            name: keycloak
            port:
              number: 8080
