apiVersion: v1
kind: Secret
metadata:
  name: admin-pw-env
stringData:
  KEYCLOAK_USER: <path:kv/data/keycloak/admin#username>
  KEYCLOAK_PASSWORD: <path:kv/data/keycloak/admin#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds-env
stringData:
  DB_VENDOR: mysql
  DB_ADDR: mysql.mysql
  DB_PORT: "3306"
  DB_DATABASE: keycloak
  DB_USER: <path:kv/data/keycloak/mysql#username>
  DB_PASSWORD: <path:kv/data/keycloak/mysql#password>
