apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jali-clarke/dev-env.git
    targetRevision: master
    path: k8s-manifests/overlay
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
