kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: qbittorrent-config
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: torrents-downloads-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: torrents-downloads
