apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: qbittorrent-config
  nfs:
    path: /mnt/storage/k8s_drive/qbittorrent
    server: atlas.lan
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  storageClassName: torrents-downloads
  nfs:
    path: /mnt/storage/data_drive/Torrents
    server: atlas.lan
