apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  template:
    spec:
      containers:
      - name: cassandra
        volumeMounts:
        - name: db
          mountPath: /var/lib/cassandra
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: cassandra-data-pvc
